# Generated by Django 5.2.7 on 2025-11-07 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback_text", models.TextField(verbose_name="Feedback Content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="courses.course",
                        verbose_name="Related Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whisper Box Feedback",
                "verbose_name_plural": "Whisper Box Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
