# Generated by Django 5.2.7 on 2025-12-04 17:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0002_initial"),
        ("outcomes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The raw score percentage achieved in the assessment.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Score (%)",
                    ),
                ),
                (
                    "lo_mastery_score",
                    models.IntegerField(
                        help_text="The 1-5 score indicating mastery level for this specific LO (1: Low, 5: High).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="LO Mastery Score (1-5)",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="courses.assessment",
                        verbose_name="Assessment",
                    ),
                ),
                (
                    "learning_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="outcomes.learningoutcome",
                        verbose_name="Learning Outcome",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade",
                "verbose_name_plural": "Grades",
                "permissions": [("can_grade", "Can enter and modify grades")],
            },
        ),
        migrations.CreateModel(
            name="GradeAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "new_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("old_mastery", models.IntegerField(blank=True, null=True)),
                ("new_mastery", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.assessment",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="grades.grade",
                    ),
                ),
                (
                    "learning_outcome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="outcomes.learningoutcome",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Computed course grade (0-100)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Grade",
                "verbose_name_plural": "Course Grades",
                "unique_together": {("student", "course")},
            },
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "assessment"], name="grades_grad_student_822f84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score_percentage__gte", 0), ("score_percentage__lte", 100)
                ),
                name="grade_score_percentage_between_0_and_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="grade",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lo_mastery_score__gte", 1), ("lo_mastery_score__lte", 5)
                ),
                name="grade_lo_mastery_between_1_and_5",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "assessment", "learning_outcome")},
        ),
    ]
