# Generated by Django 5.2.7 on 2025-12-04 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("grades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursegrade",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="coursegrade",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursegrade",
            name="student",
        ),
        migrations.RemoveField(
            model_name="gradeaudit",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="gradeaudit",
            name="changed_by",
        ),
        migrations.RemoveField(
            model_name="gradeaudit",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="gradeaudit",
            name="learning_outcome",
        ),
        migrations.RemoveField(
            model_name="gradeaudit",
            name="student",
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "Grade", "verbose_name_plural": "Grades"},
        ),
        migrations.RemoveConstraint(
            model_name="grade",
            name="grade_score_percentage_between_0_and_100",
        ),
        migrations.RemoveConstraint(
            model_name="grade",
            name="grade_lo_mastery_between_1_and_5",
        ),
        migrations.RemoveIndex(
            model_name="grade",
            name="grades_grad_student_822f84_idx",
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "assessment")},
        ),
        migrations.AlterField(
            model_name="grade",
            name="score_percentage",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Student's score for this assessment (0-100).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Score (%)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.DeleteModel(
            name="CourseGrade",
        ),
        migrations.DeleteModel(
            name="GradeAudit",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="learning_outcome",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="lo_mastery_score",
        ),
    ]
