# Generated by Django 5.2.8 on 2025-12-28 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_student'),
        ('grades', '0002_alter_coursegrade_unique_together_and_more'),
        ('outcomes', '0003_alter_learningoutcome_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='learning_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='outcomes.learningoutcome', verbose_name='Learning Outcome'),
        ),
        migrations.AddField(
            model_name='grade',
            name='lo_mastery_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='LO Mastery (1-5)'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assessment', 'learning_outcome')},
        ),
    ]
