# Generated by Django 5.2.7 on 2025-11-23 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
        ('grades', '0003_coursegrade'),
        ('outcomes', '0003_remove_studentgoal_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'assessment'], name='grades_grad_student_822f84_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score_percentage__gte', 0), ('score_percentage__lte', 100)), name='grade_score_percentage_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('lo_mastery_score__gte', 1), ('lo_mastery_score__lte', 5)), name='grade_lo_mastery_between_1_and_5'),
        ),
    ]
