# Generated by Django 5.2.8 on 2025-11-30 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_instructor'),
        ('grades', '0004_grade_grades_grad_student_822f84_idx_and_more'),
        ('outcomes', '0003_remove_studentgoal_student_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('old_mastery', models.IntegerField(blank=True, null=True)),
                ('new_mastery', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.assessment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='grades.grade')),
                ('learning_outcome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='outcomes.learningoutcome')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
