# Generated by Django 5.2.8 on 2025-12-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_gradeaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': [('can_grade', 'Can enter and modify grades')], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
    ]
