# Generated by Django 5.2.7 on 2026-01-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("INSTRUCTOR", "Instructor"),
                    ("DEPT_HEAD", "Department Head"),
                    ("ADMIN", "Admin"),
                ],
                default="STUDENT",
                max_length=20,
                verbose_name="User Role",
            ),
        ),
    ]
