# Generated by Django 5.2.7 on 2025-12-04 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MIDTERM", "Midterm"),
                            ("FINAL", "Final"),
                            ("HOMEWORK", "Homework"),
                            ("PROJECT", "Project"),
                            ("QUIZ", "Quiz"),
                            ("OTHER", "Other"),
                        ],
                        default="MIDTERM",
                        max_length=10,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The contribution percentage of this assessment to the overall course grade.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Weight Percentage (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Course Code"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Course Title"),
                ),
                (
                    "ects_credit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ECTS Credit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SLIDE", "Slide/File"),
                            ("LINK", "Link/URL"),
                            ("ANNOUNCEMENT", "Announcement"),
                        ],
                        default="SLIDE",
                        max_length=20,
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Course Material",
            },
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
