# Generated by Django 5.2.7 on 2025-11-04 10:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("outcomes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Course Code"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Course Title"),
                ),
                (
                    "ects_credit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="ECTS Credit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MIDTERM", "Midterm"),
                            ("FINAL", "Final"),
                            ("HOMEWORK", "Homework"),
                            ("PROJECT", "Project"),
                            ("QUIZ", "Quiz"),
                            ("OTHER", "Other"),
                        ],
                        default="MIDTERM",
                        max_length=10,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The contribution percentage of this assessment to the overall course grade.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Weight Percentage (%)",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.ManyToManyField(
                        related_name="assessments",
                        to="outcomes.learningoutcome",
                        verbose_name="Associated Learning Outcomes (LOs)",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "unique_together": {("course", "type")},
            },
        ),
    ]
