# Generated by Django 5.2.7 on 2025-12-04 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("outcomes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="learning_outcomes",
            field=models.ManyToManyField(
                related_name="assessments",
                to="outcomes.learningoutcome",
                verbose_name="Associated Learning Outcomes (LOs)",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_teacher": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instructed_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Instructor",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="courses.course",
                verbose_name="Course",
            ),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="courses.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("course", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("student", "course")},
        ),
    ]
