# Generated by Django 5.2.7 on 2025-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursematerial",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Link (if applicable)"
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Section Title"),
        ),
    ]
