# Generated by Django 5.2.8 on 2025-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursematerial_link_alter_coursesection_title'),
        ('outcomes', '0002_alter_learningoutcome_program_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='outcomes.learningoutcome', verbose_name='Associated Learning Outcomes (LOs)'),
        ),
    ]
