# Generated by Django 5.2.8 on 2025-12-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assessment_learning_outcomes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label / Name'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('HOMEWORK', 'Homework'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz'), ('ATTENDANCE', 'Attendance'), ('OTHER', 'Other')], default='MIDTERM', max_length=10, verbose_name='Assessment Type'),
        ),
    ]
