# Generated by Django 5.2.8 on 2025-12-28 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_enrollment_student'),
        ('outcomes', '0003_alter_learningoutcome_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_percentage', models.DecimalField(decimal_places=2, help_text="Percentage (0-100) of this assessment's weight that maps to this LO.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='LO Contribution (%) from this Assessment')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_contributions', to='courses.assessment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_contributions', to='outcomes.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment-LO Contribution',
                'verbose_name_plural': 'Assessment-LO Contributions',
                'unique_together': {('assessment', 'learning_outcome')},
            },
        ),
        migrations.AlterField(
            model_name='assessment',
            name='learning_outcomes',
            field=models.ManyToManyField(blank=True, related_name='assessments', through='courses.AssessmentLearningOutcome', to='outcomes.learningoutcome', verbose_name='Associated Learning Outcomes (LOs)'),
        ),
    ]
