# Generated by Django 5.2.8 on 2025-12-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assessmentlearningoutcome_and_more'),
        ('outcomes', '0003_alter_learningoutcome_code'),
    ]

    operations = [
        # No database operations: this migration is a placeholder to keep migration history
    ]
