# Generated by Django 5.2.8 on 2025-12-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_assessment_learning_outcomes'),
        ('outcomes', '0004_learningoutcome_created_by'),
    ]

    operations = [
        # No database operations: placeholder migration to keep history in sync
    ]
