# Generated by Django 5.2.8 on 2025-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_assessment_learning_outcomes'),
        ('outcomes', '0004_learningoutcome_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Uploaded file'),
        ),
    ]
