# Generated by Django 5.2.7 on 2025-12-04 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="PO Code"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Program Outcome",
                "verbose_name_plural": "Program Outcomes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LearningOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="LO Code")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_outcomes",
                        to="courses.course",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Outcome",
                "verbose_name_plural": "Learning Outcomes",
                "ordering": ["course", "code"],
            },
        ),
        migrations.CreateModel(
            name="LO_PO_Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Contribution (%)",
                    ),
                ),
                (
                    "learning_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outcomes.learningoutcome",
                        verbose_name="Learning Outcome",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outcomes.programoutcome",
                        verbose_name="Program Outcome",
                    ),
                ),
            ],
            options={
                "verbose_name": "LO-PO Contribution",
                "verbose_name_plural": "LO-PO Contributions",
                "unique_together": {("learning_outcome", "program_outcome")},
            },
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="program_outcomes",
            field=models.ManyToManyField(
                related_name="learning_outcomes",
                through="outcomes.LO_PO_Contribution",
                to="outcomes.programoutcome",
                verbose_name="Linked POs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="learningoutcome",
            unique_together={("course", "code")},
        ),
    ]
