# Generated by Django 5.2.7 on 2025-11-04 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="LO Code"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Explanation"),
                ),
            ],
            options={
                "verbose_name": "Learning Outcome (LO)",
                "verbose_name_plural": "Learning Outcomes (LOs)",
            },
        ),
        migrations.CreateModel(
            name="ProgramOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="PO Code"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Explanation"),
                ),
            ],
            options={
                "verbose_name": "Program Outcome (PO)",
                "verbose_name_plural": "Program Outcomes (POs)",
            },
        ),
        migrations.CreateModel(
            name="LO_PO_Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the percentage contribution this LO makes to this PO (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Contribution Percentage (%)",
                    ),
                ),
                (
                    "learning_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outcomes.learningoutcome",
                        verbose_name="Learning Outcome(LO)",
                    ),
                ),
                (
                    "program_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outcomes.programoutcome",
                        verbose_name="Program Outcome (PO)",
                    ),
                ),
            ],
            options={
                "verbose_name": "LO-PO Contribution",
                "verbose_name_plural": "LO-PO Contributions",
                "unique_together": {("learning_outcome", "program_outcome")},
            },
        ),
        migrations.AddField(
            model_name="learningoutcome",
            name="program_outcomes",
            field=models.ManyToManyField(
                related_name="learning_outcomes",
                through="outcomes.LO_PO_Contribution",
                to="outcomes.programoutcome",
            ),
        ),
    ]
