# Generated by Django 5.2.7 on 2025-11-07 18:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outcomes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningoutcome",
            options={
                "ordering": ("code",),
                "verbose_name": "Learning Outcome (LO)",
                "verbose_name_plural": "Learning Outcomes (LOs)",
            },
        ),
        migrations.AlterField(
            model_name="lo_po_contribution",
            name="learning_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lo_po_contributions",
                to="outcomes.learningoutcome",
                verbose_name="Learning Outcome(LO)",
            ),
        ),
        migrations.AlterField(
            model_name="lo_po_contribution",
            name="program_outcome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lo_po_contributions",
                to="outcomes.programoutcome",
                verbose_name="Program Outcome (PO)",
            ),
        ),
        migrations.CreateModel(
            name="StudentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_description",
                    models.CharField(max_length=255, verbose_name="Goal Description"),
                ),
                ("target_date", models.DateField(verbose_name="Target Date")),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Completion (%)",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Goal",
                "verbose_name_plural": "Student Goals",
                "ordering": ["target_date"],
            },
        ),
        migrations.CreateModel(
            name="GoalLearningOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_in_goal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The percentage of this goal focused on this specific LO.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Weight in Goal (%)",
                    ),
                ),
                (
                    "learning_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outcomes.learningoutcome",
                        verbose_name="Learning Outcome (LO)",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_outcomes",
                        to="outcomes.studentgoal",
                        verbose_name="Goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal LO Link",
                "verbose_name_plural": "Goal LO Links",
                "unique_together": {("goal", "learning_outcome")},
            },
        ),
    ]
