# Generated by Django 5.2.8 on 2025-12-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningoutcome',
            name='program_outcomes',
            field=models.ManyToManyField(blank=True, related_name='learning_outcomes', through='outcomes.LO_PO_Contribution', to='outcomes.programoutcome', verbose_name='Linked POs'),
        ),
    ]
