# Generated by Django 5.2.7 on 2025-11-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outcomes", "0002_alter_learningoutcome_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentgoal",
            name="student",
        ),
        migrations.DeleteModel(
            name="GoalLearningOutcome",
        ),
        migrations.DeleteModel(
            name="StudentGoal",
        ),
    ]
