# Generated by Django 5.2.7 on 2025-12-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outcomes", "0002_alter_learningoutcome_program_outcomes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningoutcome",
            name="code",
            field=models.CharField(blank=True, max_length=10, verbose_name="LO Code"),
        ),
    ]
