# Generated by Django 5.2.8 on 2025-12-29 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outcomes', '0003_alter_learningoutcome_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningoutcome',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_learning_outcomes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
